[workspace]
resolver = "2"
members = [
    "assemblyline-client",
    "assemblyline-markings",
    "assemblyline-models",
    "assemblyline-server", 
    "environment_template",
    "redis-objects"
]
