[package]
name = "assemblyline-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utilities
log = "*"
chrono = "*"
tempfile = "*"
rand = "*"
itertools = "*"

# Core framework
tokio = { version = "1", features = ["full"] }
futures = "*"

# Network libraries
reqwest = { version = "0.11", features = ["json"] }
poem = { version = "1.3", features = ["websocket", "openssl-tls"] }
url = "*"
tokio-tungstenite = "0.20"

# Crypto libraries
openssl = { version = "0.10" }
native-tls = "0.2"
hyper-rustls = { version = "0.23", features = [] }
rustls = "0.20"

# Database tools
elasticsearch = "8.5.0-alpha.1"
redis = { version = "0.23.0", features = ["tokio-native-tls-comp", "connection-manager"] }

# Data managing
assemblyline-models = { version = "0.1", path = "../assemblyline-models" }
serde = { version = "*", features = ["derive", "rc"] }
serde_json = "*"