[package]
name = "assemblyline-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Logging
log = "*"
flexi_logger = { version = "0.28", features=["syslog_writer"] }
gethostname = "0.4"
local-ip-address = "0.6"

# Utilities
chrono = "*"
tempfile = "*"
rand = "*"
itertools = "*"
anyhow = "*"
thiserror = "*"
bytes = "*"
parking_lot = "*"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
environment_template = "0.1"
clap = { version = "4.5", features = ["derive"] }

# Core framework
tokio = { version = "1", features = ["full"] }
futures = "*"

# Network libraries
reqwest = { version = "0.11", features = ["json"] }
poem = { version = "1.3", features = ["websocket", "openssl-tls"] }
url = "*"
tokio-tungstenite = "0.20"
http = "*"

# Crypto libraries
openssl = { version = "0.10" }
native-tls = "0.2"
hyper-rustls = { version = "0.23", features = [] }
rustls = "0.20"

# Database tools
elasticsearch = "8.5.0-alpha.1"
redis-objects = { version = "*", path = "../redis-objects" }

# Data managing
assemblyline-markings = { version = "0.1", path = "../assemblyline-markings" }
assemblyline-models = { version = "0.1", path = "../assemblyline-models", features = ["rand"] }
struct-metadata = "0.2"
serde = { version = "*", features = ["derive", "rc"] }
serde_json = "*"
serde_yaml = "*"
serde_with = "*"

# data parsing
nom = "*"
regex = "*"