[package]
name = "assemblyline-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "*"
poem = { version = "1.3", features = ["websocket", "openssl-tls"] }
openssl = { version = "0.10" }
native-tls = "0.2"
hyper-rustls = { version = "0.23", features = [] }
rustls = "0.20"
chrono = "*"
serde = { version = "*", features = ["derive"] }

assemblyline-models = "0.1"