name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: unittest-samples
  # Try to checkout the matching branch, if the command fails, don't care.
  - name: "BRANCH_NAME"
    value: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''), 'main')]

resources:
  repositories:
    - repository: unittest-samples
      type: github
      name: $(unittest_samples_repository)
      ref: main
      endpoint: github-repo-sa
      trigger: ["*"]

jobs:
  # - job: test_client
  #   dependsOn: []
  #   displayName: Test Client
  #   steps:
  #     - checkout: self
  #     - script: |
  #         set -e
  #         docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
  #         docker run -v ${PWD}:/usr/src/ \
  #                    --network=host \
  #                    cccstemp.azurecr.io/assemblyline-rust-builder:latest \
  #                    bash -c 'cd assemblyline-client; cargo test --target-dir /out'
  #       displayName: Test Client
  - job: test_filestore
    dependsOn: []
    displayName: Test Filestore
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          # Start all services except cargo test
          docker compose up -d --wait $(docker compose config --services | grep -v cargo_test)

          # Run cargo tests
          docker compose run --build cargo_test
        displayName: Test Filestore
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-filestore
  - job: test_markings
    dependsOn: []
    displayName: Test Markings
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     -w /usr/src/ \
                     rust:1.96-trixie \
                     bash -c 'cd assemblyline-markings; cargo test --target-dir /out'
        displayName: Test Markings
  # - job: test_models
  #   dependsOn: []
  #   displayName: Test Models
  #   steps:
  #     - checkout: self
  #     - script: |
  #         set -e
  #         docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
  #         docker run -v ${PWD}:/usr/src/ \
  #                    --network=host \
  #                    cccstemp.azurecr.io/assemblyline-rust-builder:latest \
  #                    bash -c 'cd assemblyline-models; cargo test --target-dir /out'
  #       displayName: Test Models
  - job: test_server
    dependsOn: []
    displayName: Test Server
    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: unittest-samples
        fetchDepth: 1
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          # Start all services except cargo test
          docker compose up -d --wait $(docker compose config --services | grep -v cargo_test)

          # Run cargo tests
          docker compose run --build -e SAMPLES_LOCATION=/tmp/samples -v $SYSTEM_DEFAULTWORKINGDIRECTORY/unittest-samples:/tmp/samples cargo_test
        displayName: Test Server
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust/assemblyline-server
  - job: test_environment_template
    dependsOn: []
    displayName: Test Environment Template
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     -w /usr/src/ \
                     rust:1.96-trixie \
                     bash -c 'cd environment_template; cargo test --target-dir /out'
        displayName: Test Environment Template
  - job: test_redis
    dependsOn: []
    displayName: Test Redis
    steps:
      - checkout: self
        fetchDepth: 1
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          # Start all services except cargo test
          docker compose up -d --wait $(docker compose config --services | grep -v cargo_test)

          # Run cargo tests
          docker compose run --build cargo_test
        displayName: Test Redis
        workingDirectory: $(System.DefaultWorkingDirectory)/redis-objects
