name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

# variables:
#   # Try to checkout the matching branch, if the command fails, don't care.
#   BRANCH_NAME: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''))]

jobs:
  # - job: test_client
  #   dependsOn: []
  #   displayName: Test Client
  #   steps:
  #     - checkout: self
  #     - script: |
  #         set -e
  #         docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
  #         docker run -v ${PWD}:/usr/src/ \
  #                    --network=host \
  #                    cccstemp.azurecr.io/assemblyline-rust-builder:latest \
  #                    bash -c 'cd assemblyline-client; cargo test --target-dir /out'
  #       workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
  #       displayName: Test Client
  - job: test_filestore
    dependsOn: []
    displayName: Test Filestore
    steps:
      - checkout: self
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
          (cd assemblyline-filestore; docker compose up -d --wait)
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                     bash -c 'cd assemblyline-filestore; cargo test --target-dir /out'
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
        displayName: Test Filestore
  - job: test_markings
    dependsOn: []
    displayName: Test Markings
    steps:
      - checkout: self
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                     bash -c 'cd assemblyline-markings; cargo test --target-dir /out'
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
        displayName: Test Markings
  # - job: test_models
  #   dependsOn: []
  #   displayName: Test Models
  #   steps:
  #     - checkout: self
  #     - script: |
  #         set -e
  #         docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
  #         docker run -v ${PWD}:/usr/src/ \
  #                    --network=host \
  #                    cccstemp.azurecr.io/assemblyline-rust-builder:latest \
  #                    bash -c 'cd assemblyline-models; cargo test --target-dir /out'
  #       workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
  #       displayName: Test Models
  - job: test_server
    dependsOn: []
    displayName: Test Server
    steps:
      - checkout: self
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
          (cd assemblyline-server; docker compose up -d --wait)
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                     bash -c 'cd assemblyline-server; cargo test --target-dir /out'
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
        displayName: Test Server
  - job: test_environment_template
    dependsOn: []
    displayName: Test Environment Template
    steps:
      - checkout: self
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                     bash -c 'cd environment_template; cargo test --target-dir /out'
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
        displayName: Test Environment Template
  - job: test_redis
    dependsOn: []
    displayName: Test Redis
    steps:
      - checkout: self
      - task: Docker@2
        displayName: Login to docker registry
        inputs:
          command: login
          containerRegistry: cccstemp
      - script: |
          set -e
          docker pull cccstemp.azurecr.io/assemblyline-rust-builder:latest
          (cd redis-objects; docker compose up -d --wait)
          docker run -v ${PWD}:/usr/src/ \
                     --network=host \
                     cccstemp.azurecr.io/assemblyline-rust-builder:latest \
                     bash -c 'cd redis-objects; cargo test --target-dir /out'
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-rust
        displayName: Test Redis
