[package]
name = "assemblyline-client"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = """A client for the Assemblyline malware analysis platform."""

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
async-recursion = { version = "1" }