[package]
name = "assemblyline-client"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = """A client for the Assemblyline malware analysis platform."""

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies", "multipart", "stream"] }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"

tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
async-recursion = { version = "1" }

url = "2"
