[package]
name = "assemblyline-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive", "std"] }
serde_with = "3.3"
serde_json = "1.0"
strum = { version = "0.25", features = ["derive"] }

chrono = { version = "0.4", features = ["serde"] }

struct-metadata = { version = "0.1" }